image: Visual Studio 2017

before_build:
  - gitversion /l console /output buildserver

build_script:
  - ps: src\build.ps1 $env:GitVersion_NuGetVersion

artifacts:
  - path: artifacts\*.nupkg

deploy:
  provider: Environment
  name: nuget.org
  on:
    appveyor_repo_tag: true
